/* Generated by Yosys 0.13+28 (git sha1 0a6e2bd5d, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module cla(A, B, cin, S, cout);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  wire [4:0] C;
  wire [3:0] G;
  wire [3:0] P;
  output [3:0] S;
  wire [3:0] S;
  input cin;
  wire cin;
  output cout;
  wire cout;
  wire [4:0] \gen_c.C ;
  wire [3:0] \gen_c.G ;
  wire [3:0] \gen_c.P ;
  wire \gen_c.cin ;
  sky130_fd_sc_hd__and2_0 _00_ (
    .A(B[0]),
    .B(A[0]),
    .X(G[0])
  );
  sky130_fd_sc_hd__xor2_1 _01_ (
    .A(B[0]),
    .B(A[0]),
    .X(P[0])
  );
  sky130_fd_sc_hd__and2_0 _02_ (
    .A(B[1]),
    .B(A[1]),
    .X(G[1])
  );
  sky130_fd_sc_hd__xor2_1 _03_ (
    .A(B[1]),
    .B(A[1]),
    .X(P[1])
  );
  sky130_fd_sc_hd__and2_0 _04_ (
    .A(B[2]),
    .B(A[2]),
    .X(G[2])
  );
  sky130_fd_sc_hd__xor2_1 _05_ (
    .A(B[2]),
    .B(A[2]),
    .X(P[2])
  );
  sky130_fd_sc_hd__and2_0 _06_ (
    .A(B[3]),
    .B(A[3]),
    .X(G[3])
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(B[3]),
    .B(A[3]),
    .X(P[3])
  );
  sky130_fd_sc_hd__xor3_1 _08_ (
    .A(B[0]),
    .B(A[0]),
    .C(C[0]),
    .X(S[0])
  );
  sky130_fd_sc_hd__xor3_1 _09_ (
    .A(B[1]),
    .B(A[1]),
    .C(C[1]),
    .X(S[1])
  );
  sky130_fd_sc_hd__xor3_1 _10_ (
    .A(B[2]),
    .B(A[2]),
    .C(C[2]),
    .X(S[2])
  );
  sky130_fd_sc_hd__xor3_1 _11_ (
    .A(B[3]),
    .B(A[3]),
    .C(C[3]),
    .X(S[3])
  );
  sky130_fd_sc_hd__a21o_1 _12_ (
    .A1(\gen_c.cin ),
    .A2(\gen_c.P [0]),
    .B1(\gen_c.G [0]),
    .X(\gen_c.C [1])
  );
  sky130_fd_sc_hd__a21o_1 _13_ (
    .A1(\gen_c.P [1]),
    .A2(\gen_c.C [1]),
    .B1(\gen_c.G [1]),
    .X(\gen_c.C [2])
  );
  sky130_fd_sc_hd__a21o_1 _14_ (
    .A1(\gen_c.P [2]),
    .A2(\gen_c.C [2]),
    .B1(\gen_c.G [2]),
    .X(\gen_c.C [3])
  );
  sky130_fd_sc_hd__a21o_1 _15_ (
    .A1(\gen_c.P [3]),
    .A2(\gen_c.C [3]),
    .B1(\gen_c.G [3]),
    .X(\gen_c.C [4])
  );
  assign cout = C[4];
  assign \gen_c.C [0] = \gen_c.cin ;
  assign C = \gen_c.C ;
  assign \gen_c.G  = G;
  assign \gen_c.P  = P;
  assign \gen_c.cin  = cin;
endmodule
