/* Generated by Yosys 0.13+28 (git sha1 0a6e2bd5d, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module rca(a, b, sum, co);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  wire c1;
  wire c2;
  wire c3;
  output co;
  wire co;
  wire \fa1.a ;
  wire \fa1.b ;
  wire \fa1.c1 ;
  wire \fa1.c2 ;
  wire \fa1.cin ;
  wire \fa1.co ;
  wire \fa1.ha1.a ;
  wire \fa1.ha1.b ;
  wire \fa1.ha1.co ;
  wire \fa1.ha1.sum ;
  wire \fa1.ha2.a ;
  wire \fa1.ha2.b ;
  wire \fa1.ha2.co ;
  wire \fa1.ha2.sum ;
  wire \fa1.s1 ;
  wire \fa1.sum ;
  wire \fa2.a ;
  wire \fa2.b ;
  wire \fa2.c1 ;
  wire \fa2.c2 ;
  wire \fa2.cin ;
  wire \fa2.co ;
  wire \fa2.ha1.a ;
  wire \fa2.ha1.b ;
  wire \fa2.ha1.co ;
  wire \fa2.ha1.sum ;
  wire \fa2.ha2.a ;
  wire \fa2.ha2.b ;
  wire \fa2.ha2.co ;
  wire \fa2.ha2.sum ;
  wire \fa2.s1 ;
  wire \fa2.sum ;
  wire \fa3.a ;
  wire \fa3.b ;
  wire \fa3.c1 ;
  wire \fa3.c2 ;
  wire \fa3.cin ;
  wire \fa3.co ;
  wire \fa3.ha1.a ;
  wire \fa3.ha1.b ;
  wire \fa3.ha1.co ;
  wire \fa3.ha1.sum ;
  wire \fa3.ha2.a ;
  wire \fa3.ha2.b ;
  wire \fa3.ha2.co ;
  wire \fa3.ha2.sum ;
  wire \fa3.s1 ;
  wire \fa3.sum ;
  wire \fa4.a ;
  wire \fa4.b ;
  wire \fa4.c1 ;
  wire \fa4.c2 ;
  wire \fa4.cin ;
  wire \fa4.co ;
  wire \fa4.ha1.a ;
  wire \fa4.ha1.b ;
  wire \fa4.ha1.co ;
  wire \fa4.ha1.sum ;
  wire \fa4.ha2.a ;
  wire \fa4.ha2.b ;
  wire \fa4.ha2.co ;
  wire \fa4.ha2.sum ;
  wire \fa4.s1 ;
  wire \fa4.sum ;
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _00_ (
    .A(\fa1.c2 ),
    .SLEEP(\fa1.c1 ),
    .X(\fa1.co )
  );
  sky130_fd_sc_hd__and2_0 _01_ (
    .A(\fa1.ha1.b ),
    .B(\fa1.ha1.a ),
    .X(\fa1.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _02_ (
    .A(\fa1.ha1.b ),
    .B(\fa1.ha1.a ),
    .X(\fa1.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _03_ (
    .A(\fa1.ha2.b ),
    .B(\fa1.ha2.a ),
    .X(\fa1.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _04_ (
    .A(\fa1.ha2.b ),
    .B(\fa1.ha2.a ),
    .X(\fa1.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _05_ (
    .A(\fa2.c2 ),
    .SLEEP(\fa2.c1 ),
    .X(\fa2.co )
  );
  sky130_fd_sc_hd__and2_0 _06_ (
    .A(\fa2.ha1.b ),
    .B(\fa2.ha1.a ),
    .X(\fa2.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(\fa2.ha1.b ),
    .B(\fa2.ha1.a ),
    .X(\fa2.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _08_ (
    .A(\fa2.ha2.b ),
    .B(\fa2.ha2.a ),
    .X(\fa2.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(\fa2.ha2.b ),
    .B(\fa2.ha2.a ),
    .X(\fa2.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _10_ (
    .A(\fa3.c2 ),
    .SLEEP(\fa3.c1 ),
    .X(\fa3.co )
  );
  sky130_fd_sc_hd__and2_0 _11_ (
    .A(\fa3.ha1.b ),
    .B(\fa3.ha1.a ),
    .X(\fa3.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(\fa3.ha1.b ),
    .B(\fa3.ha1.a ),
    .X(\fa3.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _13_ (
    .A(\fa3.ha2.b ),
    .B(\fa3.ha2.a ),
    .X(\fa3.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(\fa3.ha2.b ),
    .B(\fa3.ha2.a ),
    .X(\fa3.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _15_ (
    .A(\fa4.c2 ),
    .SLEEP(\fa4.c1 ),
    .X(\fa4.co )
  );
  sky130_fd_sc_hd__and2_0 _16_ (
    .A(\fa4.ha1.b ),
    .B(\fa4.ha1.a ),
    .X(\fa4.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(\fa4.ha1.b ),
    .B(\fa4.ha1.a ),
    .X(\fa4.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _18_ (
    .A(\fa4.ha2.b ),
    .B(\fa4.ha2.a ),
    .X(\fa4.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(\fa4.ha2.b ),
    .B(\fa4.ha2.a ),
    .X(\fa4.ha2.sum )
  );
  assign \fa4.ha2.a  = \fa4.cin ;
  assign \fa4.ha2.b  = \fa4.s1 ;
  assign \fa4.c2  = \fa4.ha2.co ;
  assign \fa4.sum  = \fa4.ha2.sum ;
  assign \fa4.ha1.a  = \fa4.a ;
  assign \fa4.ha1.b  = \fa4.b ;
  assign \fa4.c1  = \fa4.ha1.co ;
  assign \fa4.s1  = \fa4.ha1.sum ;
  assign \fa4.a  = a[3];
  assign \fa4.b  = b[3];
  assign \fa4.cin  = c3;
  assign co = \fa4.co ;
  assign sum[3] = \fa4.sum ;
  assign \fa3.ha2.a  = \fa3.cin ;
  assign \fa3.ha2.b  = \fa3.s1 ;
  assign \fa3.c2  = \fa3.ha2.co ;
  assign \fa3.sum  = \fa3.ha2.sum ;
  assign \fa3.ha1.a  = \fa3.a ;
  assign \fa3.ha1.b  = \fa3.b ;
  assign \fa3.c1  = \fa3.ha1.co ;
  assign \fa3.s1  = \fa3.ha1.sum ;
  assign \fa3.a  = a[2];
  assign \fa3.b  = b[2];
  assign \fa3.cin  = c2;
  assign c3 = \fa3.co ;
  assign sum[2] = \fa3.sum ;
  assign \fa2.ha2.a  = \fa2.cin ;
  assign \fa2.ha2.b  = \fa2.s1 ;
  assign \fa2.c2  = \fa2.ha2.co ;
  assign \fa2.sum  = \fa2.ha2.sum ;
  assign \fa2.ha1.a  = \fa2.a ;
  assign \fa2.ha1.b  = \fa2.b ;
  assign \fa2.c1  = \fa2.ha1.co ;
  assign \fa2.s1  = \fa2.ha1.sum ;
  assign \fa2.a  = a[1];
  assign \fa2.b  = b[1];
  assign \fa2.cin  = c1;
  assign c2 = \fa2.co ;
  assign sum[1] = \fa2.sum ;
  assign \fa1.ha2.a  = \fa1.cin ;
  assign \fa1.ha2.b  = \fa1.s1 ;
  assign \fa1.c2  = \fa1.ha2.co ;
  assign \fa1.sum  = \fa1.ha2.sum ;
  assign \fa1.ha1.a  = \fa1.a ;
  assign \fa1.ha1.b  = \fa1.b ;
  assign \fa1.c1  = \fa1.ha1.co ;
  assign \fa1.s1  = \fa1.ha1.sum ;
  assign \fa1.a  = a[0];
  assign \fa1.b  = b[0];
  assign \fa1.cin  = 1'h0;
  assign c1 = \fa1.co ;
  assign sum[0] = \fa1.sum ;
endmodule
