/* Generated by Yosys 0.13+28 (git sha1 0a6e2bd5d, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module csa(a, b, sum, co);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  wire c1;
  wire c2;
  wire c3;
  wire c4;
  output co;
  wire co;
  wire \fa1.a ;
  wire \fa1.b ;
  wire \fa1.c1 ;
  wire \fa1.c2 ;
  wire \fa1.cin ;
  wire \fa1.co ;
  wire \fa1.ha1.a ;
  wire \fa1.ha1.b ;
  wire \fa1.ha1.co ;
  wire \fa1.ha1.sum ;
  wire \fa1.ha2.a ;
  wire \fa1.ha2.b ;
  wire \fa1.ha2.co ;
  wire \fa1.ha2.sum ;
  wire \fa1.s1 ;
  wire \fa1.sum ;
  wire \fa2.a ;
  wire \fa2.b ;
  wire \fa2.c1 ;
  wire \fa2.c2 ;
  wire \fa2.cin ;
  wire \fa2.co ;
  wire \fa2.ha1.a ;
  wire \fa2.ha1.b ;
  wire \fa2.ha1.co ;
  wire \fa2.ha1.sum ;
  wire \fa2.ha2.a ;
  wire \fa2.ha2.b ;
  wire \fa2.ha2.co ;
  wire \fa2.ha2.sum ;
  wire \fa2.s1 ;
  wire \fa2.sum ;
  wire \fa3.a ;
  wire \fa3.b ;
  wire \fa3.c1 ;
  wire \fa3.c2 ;
  wire \fa3.cin ;
  wire \fa3.co ;
  wire \fa3.ha1.a ;
  wire \fa3.ha1.b ;
  wire \fa3.ha1.co ;
  wire \fa3.ha1.sum ;
  wire \fa3.ha2.a ;
  wire \fa3.ha2.b ;
  wire \fa3.ha2.co ;
  wire \fa3.ha2.sum ;
  wire \fa3.s1 ;
  wire \fa3.sum ;
  wire \fa4.a ;
  wire \fa4.b ;
  wire \fa4.c1 ;
  wire \fa4.c2 ;
  wire \fa4.cin ;
  wire \fa4.co ;
  wire \fa4.ha1.a ;
  wire \fa4.ha1.b ;
  wire \fa4.ha1.co ;
  wire \fa4.ha1.sum ;
  wire \fa4.ha2.a ;
  wire \fa4.ha2.b ;
  wire \fa4.ha2.co ;
  wire \fa4.ha2.sum ;
  wire \fa4.s1 ;
  wire \fa4.sum ;
  wire \fa5.a ;
  wire \fa5.b ;
  wire \fa5.c1 ;
  wire \fa5.c2 ;
  wire \fa5.cin ;
  wire \fa5.co ;
  wire \fa5.ha1.a ;
  wire \fa5.ha1.b ;
  wire \fa5.ha1.co ;
  wire \fa5.ha1.sum ;
  wire \fa5.ha2.a ;
  wire \fa5.ha2.b ;
  wire \fa5.ha2.co ;
  wire \fa5.ha2.sum ;
  wire \fa5.s1 ;
  wire \fa5.sum ;
  wire \fa6.a ;
  wire \fa6.b ;
  wire \fa6.c1 ;
  wire \fa6.c2 ;
  wire \fa6.cin ;
  wire \fa6.co ;
  wire \fa6.ha1.a ;
  wire \fa6.ha1.b ;
  wire \fa6.ha1.co ;
  wire \fa6.ha1.sum ;
  wire \fa6.ha2.a ;
  wire \fa6.ha2.b ;
  wire \fa6.ha2.co ;
  wire \fa6.ha2.sum ;
  wire \fa6.s1 ;
  wire \fa6.sum ;
  wire \fa7.a ;
  wire \fa7.b ;
  wire \fa7.c1 ;
  wire \fa7.c2 ;
  wire \fa7.cin ;
  wire \fa7.co ;
  wire \fa7.ha1.a ;
  wire \fa7.ha1.b ;
  wire \fa7.ha1.co ;
  wire \fa7.ha1.sum ;
  wire \fa7.ha2.a ;
  wire \fa7.ha2.b ;
  wire \fa7.ha2.co ;
  wire \fa7.ha2.sum ;
  wire \fa7.s1 ;
  wire \fa7.sum ;
  wire \ha1.a ;
  wire \ha1.b ;
  wire \ha1.co ;
  wire \ha1.sum ;
  wire m1;
  wire m2;
  wire m3;
  wire n1;
  wire n2;
  wire n3;
  wire n4;
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _00_ (
    .A(\fa1.c2 ),
    .SLEEP(\fa1.c1 ),
    .X(\fa1.co )
  );
  sky130_fd_sc_hd__and2_0 _01_ (
    .A(\fa1.ha1.b ),
    .B(\fa1.ha1.a ),
    .X(\fa1.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _02_ (
    .A(\fa1.ha1.b ),
    .B(\fa1.ha1.a ),
    .X(\fa1.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _03_ (
    .A(\fa1.ha2.b ),
    .B(\fa1.ha2.a ),
    .X(\fa1.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _04_ (
    .A(\fa1.ha2.b ),
    .B(\fa1.ha2.a ),
    .X(\fa1.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _05_ (
    .A(\fa2.c2 ),
    .SLEEP(\fa2.c1 ),
    .X(\fa2.co )
  );
  sky130_fd_sc_hd__and2_0 _06_ (
    .A(\fa2.ha1.b ),
    .B(\fa2.ha1.a ),
    .X(\fa2.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(\fa2.ha1.b ),
    .B(\fa2.ha1.a ),
    .X(\fa2.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _08_ (
    .A(\fa2.ha2.b ),
    .B(\fa2.ha2.a ),
    .X(\fa2.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(\fa2.ha2.b ),
    .B(\fa2.ha2.a ),
    .X(\fa2.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _10_ (
    .A(\fa3.c2 ),
    .SLEEP(\fa3.c1 ),
    .X(\fa3.co )
  );
  sky130_fd_sc_hd__and2_0 _11_ (
    .A(\fa3.ha1.b ),
    .B(\fa3.ha1.a ),
    .X(\fa3.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(\fa3.ha1.b ),
    .B(\fa3.ha1.a ),
    .X(\fa3.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _13_ (
    .A(\fa3.ha2.b ),
    .B(\fa3.ha2.a ),
    .X(\fa3.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(\fa3.ha2.b ),
    .B(\fa3.ha2.a ),
    .X(\fa3.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _15_ (
    .A(\fa4.c2 ),
    .SLEEP(\fa4.c1 ),
    .X(\fa4.co )
  );
  sky130_fd_sc_hd__and2_0 _16_ (
    .A(\fa4.ha1.b ),
    .B(\fa4.ha1.a ),
    .X(\fa4.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(\fa4.ha1.b ),
    .B(\fa4.ha1.a ),
    .X(\fa4.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _18_ (
    .A(\fa4.ha2.b ),
    .B(\fa4.ha2.a ),
    .X(\fa4.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(\fa4.ha2.b ),
    .B(\fa4.ha2.a ),
    .X(\fa4.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _20_ (
    .A(\fa5.c2 ),
    .SLEEP(\fa5.c1 ),
    .X(\fa5.co )
  );
  sky130_fd_sc_hd__and2_0 _21_ (
    .A(\fa5.ha1.b ),
    .B(\fa5.ha1.a ),
    .X(\fa5.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _22_ (
    .A(\fa5.ha1.b ),
    .B(\fa5.ha1.a ),
    .X(\fa5.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _23_ (
    .A(\fa5.ha2.b ),
    .B(\fa5.ha2.a ),
    .X(\fa5.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _24_ (
    .A(\fa5.ha2.b ),
    .B(\fa5.ha2.a ),
    .X(\fa5.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _25_ (
    .A(\fa6.c2 ),
    .SLEEP(\fa6.c1 ),
    .X(\fa6.co )
  );
  sky130_fd_sc_hd__and2_0 _26_ (
    .A(\fa6.ha1.b ),
    .B(\fa6.ha1.a ),
    .X(\fa6.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _27_ (
    .A(\fa6.ha1.b ),
    .B(\fa6.ha1.a ),
    .X(\fa6.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _28_ (
    .A(\fa6.ha2.b ),
    .B(\fa6.ha2.a ),
    .X(\fa6.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(\fa6.ha2.b ),
    .B(\fa6.ha2.a ),
    .X(\fa6.ha2.sum )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _30_ (
    .A(\fa7.c2 ),
    .SLEEP(\fa7.c1 ),
    .X(\fa7.co )
  );
  sky130_fd_sc_hd__and2_0 _31_ (
    .A(\fa7.ha1.b ),
    .B(\fa7.ha1.a ),
    .X(\fa7.ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _32_ (
    .A(\fa7.ha1.b ),
    .B(\fa7.ha1.a ),
    .X(\fa7.ha1.sum )
  );
  sky130_fd_sc_hd__and2_0 _33_ (
    .A(\fa7.ha2.b ),
    .B(\fa7.ha2.a ),
    .X(\fa7.ha2.co )
  );
  sky130_fd_sc_hd__xor2_1 _34_ (
    .A(\fa7.ha2.b ),
    .B(\fa7.ha2.a ),
    .X(\fa7.ha2.sum )
  );
  sky130_fd_sc_hd__and2_0 _35_ (
    .A(\ha1.b ),
    .B(\ha1.a ),
    .X(\ha1.co )
  );
  sky130_fd_sc_hd__xor2_1 _36_ (
    .A(\ha1.b ),
    .B(\ha1.a ),
    .X(\ha1.sum )
  );
  assign \ha1.a  = m1;
  assign \ha1.b  = n1;
  assign c1 = \ha1.co ;
  assign sum[1] = \ha1.sum ;
  assign \fa7.ha2.a  = \fa7.cin ;
  assign \fa7.ha2.b  = \fa7.s1 ;
  assign \fa7.c2  = \fa7.ha2.co ;
  assign \fa7.sum  = \fa7.ha2.sum ;
  assign \fa7.ha1.a  = \fa7.a ;
  assign \fa7.ha1.b  = \fa7.b ;
  assign \fa7.c1  = \fa7.ha1.co ;
  assign \fa7.s1  = \fa7.ha1.sum ;
  assign \fa7.a  = 1'h0;
  assign \fa7.b  = n4;
  assign \fa7.cin  = c3;
  assign c4 = \fa7.co ;
  assign co = \fa7.sum ;
  assign \fa6.ha2.a  = \fa6.cin ;
  assign \fa6.ha2.b  = \fa6.s1 ;
  assign \fa6.c2  = \fa6.ha2.co ;
  assign \fa6.sum  = \fa6.ha2.sum ;
  assign \fa6.ha1.a  = \fa6.a ;
  assign \fa6.ha1.b  = \fa6.b ;
  assign \fa6.c1  = \fa6.ha1.co ;
  assign \fa6.s1  = \fa6.ha1.sum ;
  assign \fa6.a  = m3;
  assign \fa6.b  = n3;
  assign \fa6.cin  = c2;
  assign c3 = \fa6.co ;
  assign sum[3] = \fa6.sum ;
  assign \fa5.ha2.a  = \fa5.cin ;
  assign \fa5.ha2.b  = \fa5.s1 ;
  assign \fa5.c2  = \fa5.ha2.co ;
  assign \fa5.sum  = \fa5.ha2.sum ;
  assign \fa5.ha1.a  = \fa5.a ;
  assign \fa5.ha1.b  = \fa5.b ;
  assign \fa5.c1  = \fa5.ha1.co ;
  assign \fa5.s1  = \fa5.ha1.sum ;
  assign \fa5.a  = m2;
  assign \fa5.b  = n2;
  assign \fa5.cin  = c1;
  assign c2 = \fa5.co ;
  assign sum[2] = \fa5.sum ;
  assign \fa4.ha2.a  = \fa4.cin ;
  assign \fa4.ha2.b  = \fa4.s1 ;
  assign \fa4.c2  = \fa4.ha2.co ;
  assign \fa4.sum  = \fa4.ha2.sum ;
  assign \fa4.ha1.a  = \fa4.a ;
  assign \fa4.ha1.b  = \fa4.b ;
  assign \fa4.c1  = \fa4.ha1.co ;
  assign \fa4.s1  = \fa4.ha1.sum ;
  assign \fa4.a  = a[3];
  assign \fa4.b  = b[3];
  assign \fa4.cin  = 1'h0;
  assign n4 = \fa4.co ;
  assign m3 = \fa4.sum ;
  assign \fa3.ha2.a  = \fa3.cin ;
  assign \fa3.ha2.b  = \fa3.s1 ;
  assign \fa3.c2  = \fa3.ha2.co ;
  assign \fa3.sum  = \fa3.ha2.sum ;
  assign \fa3.ha1.a  = \fa3.a ;
  assign \fa3.ha1.b  = \fa3.b ;
  assign \fa3.c1  = \fa3.ha1.co ;
  assign \fa3.s1  = \fa3.ha1.sum ;
  assign \fa3.a  = a[2];
  assign \fa3.b  = b[2];
  assign \fa3.cin  = 1'h0;
  assign n3 = \fa3.co ;
  assign m2 = \fa3.sum ;
  assign \fa2.ha2.a  = \fa2.cin ;
  assign \fa2.ha2.b  = \fa2.s1 ;
  assign \fa2.c2  = \fa2.ha2.co ;
  assign \fa2.sum  = \fa2.ha2.sum ;
  assign \fa2.ha1.a  = \fa2.a ;
  assign \fa2.ha1.b  = \fa2.b ;
  assign \fa2.c1  = \fa2.ha1.co ;
  assign \fa2.s1  = \fa2.ha1.sum ;
  assign \fa2.a  = a[1];
  assign \fa2.b  = b[1];
  assign \fa2.cin  = 1'h0;
  assign n2 = \fa2.co ;
  assign m1 = \fa2.sum ;
  assign \fa1.ha2.a  = \fa1.cin ;
  assign \fa1.ha2.b  = \fa1.s1 ;
  assign \fa1.c2  = \fa1.ha2.co ;
  assign \fa1.sum  = \fa1.ha2.sum ;
  assign \fa1.ha1.a  = \fa1.a ;
  assign \fa1.ha1.b  = \fa1.b ;
  assign \fa1.c1  = \fa1.ha1.co ;
  assign \fa1.s1  = \fa1.ha1.sum ;
  assign \fa1.a  = a[0];
  assign \fa1.b  = b[0];
  assign \fa1.cin  = 1'h0;
  assign n1 = \fa1.co ;
  assign sum[0] = \fa1.sum ;
endmodule
